
spring:
    application:
        name: demoRedis-STG


    redis: 
        database: 0 # redis 数据库索引（默认为0）    
        host: 192.168.20.81
        port: 6379
        password:
        timeout: 1000
        pool:
            maxActive: 200 # 连接池最大连接数（使用负值表示没有限制）
            maxWait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
            maxIdle: 10 # 连接池中的最大空闲连接
            minIdle: 0 # 连接池中的最小空闲连接

app:
    log:
        path: d:/logs/
        level: info

